export enum Mood {
    WORST_DAY_EVER = 0,
    AWFUL = 1,
    TERRIBLE = 1,
    SAD = 2,
    WORSE_THAN_AVERAGE = 2,
    TIRED = -1,
    SICK = -1,
    STRESSED = 3,
    ANXIOUS = 3,
    AVERAGE = 4,
    OKAY = 4,
    HAPPY = 5,
    BETTER_THAN_AVERAGE = 5,
    AMAZING = 6,
    WONDERFUL = 6,
}
